"""empty message

Revision ID: 4c31d77022f8
Revises: 2ba67af1b256
Create Date: 2023-09-21 19:53:20.687518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c31d77022f8'
down_revision = '2ba67af1b256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=180), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=180), nullable=False))
        batch_op.create_unique_constraint(None, ['salt'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('salt')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
