"""empty message

Revision ID: 9510f6268278
Revises: b2a69561b87b
Create Date: 2023-09-21 20:13:43.729416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9510f6268278'
down_revision = 'b2a69561b87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
