"""empty message

Revision ID: a549b3a278b2
Revises: 9510f6268278
Create Date: 2023-09-22 23:05:50.956510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a549b3a278b2'
down_revision = '9510f6268278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_constraint('user_salt_key', type_='unique')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=180), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=180), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=180), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_salt_key', ['salt'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
